SELECT * FROM EMPLOYEE_BKP
UPDATE EMPLOYEE_BKP SET EMAILID='SANGITAADAK2002@GMAIL.COM'

UPDATE EMPLOYEE_BKP SET EMAILID='SANGITAADAK2001@GMAIL.COM' WHERE EID=102
UPDATE EMPLOYEE_BKP SET AGE=56,GRADE='A' WHERE EID=103


UPDATE EMPLOYEE_BKP SET AGE=67 WHERE EID IN (105,107)

DELETE FROM EMPLOYEE_BKP WHERE EID=101

DATA OF DATA ->METADATA

ALTER TABLE EMPLOYEE_BKP 
ALTER COLUMN EMAILID VARCHAR(50)

ALTER TABLE EMPLOYEE_BKP 
DROP COLUMN EMAILID

SELECT * INTO E1 FROM EMPLOYEE
